### PR TITLE
Fix #323 -  Make dropdownenum dynamic

### LINKED ISSUE #323: Status field is dependent on state field but it not responding to changes
#### Issue

he status field in the Cases module is showing all values no matter what value is selected in the State field.

#### Expected Behavior

“New” and “In progress” Status drop-down values will be displayed when the State field is set to “Open”.
“Resolved” and “Cancelled” Status field drop-down values will be displayed when the State field is set to “Closed”.

#### Actual Behavior

The status field in the Cases module is showing all values no matter what value is selected in the State field.

#### Possible Fix

checkAndInitAsDynamicEnum() method need to be added to dropdownenum.component. Because the method checks the values depending on a dependant field.

#### Steps to Reproduce

1. In base-field.manifest.ts file change following:
   From :
    'enum.detail': EnumDetailFieldComponent,
    'enum.edit': EnumEditFieldComponent,
   To: 
   'enum.detail': DropdownEnumDetailFieldComponent,
    'enum.edit': DropdownEnumEditFieldComponent,
2. In editview, select State and check Status field. You ll see all values.
3.Select another value in State, and still you will see all the values

#### Context

Status needs to be dynamic dependent on State field. This is a low priority.

#### Your Environment

* SuiteCRM Version used: 8.3.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 115.0.5790.171 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): Wamp Server, PHP 7.4.33, MariaDB 10.4.12
* Operating System and version (e.g Ubuntu 16.04): Windows 11

### PR DESCRIPTION
**Pull request by yunusyerli1**
## Description

`checkAndInitAsDynamicEnum();` method has been added to dropdownenum.component #323 

## Motivation and Context

The status field in the Cases module is showing all values no matter what value is selected in the State field.

## How To Test This

In base-field.manifest.ts file change following:
From :
'enum.detail': EnumDetailFieldComponent,
'enum.edit': EnumEditFieldComponent,
To:
'enum.detail': DropdownEnumDetailFieldComponent,
'enum.edit': DropdownEnumEditFieldComponent,
In editview, select State and check Status field. You ll see all values.
Select another value in State, and still you will see all the values

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by clemente-raposo — DISMISSED** [review]
LGTM

**Comment by clemente-raposo** [comment]
@johnM2401 this wasn't merged because it had issues if I'm not mistaken. Correct?

**Comment by johnM2401** [comment]
Hey @clemente-raposo !

Yeah, I believe that's right.

As you say, the child Dynamic Dropdown wouldn't save any values.

**Comment by yunusyerli1** [comment]
I will check this.

**Comment by yunusyerli1** [comment]
Moved to #382 MR.

**Pull request closed without merging**
