### PR TITLE
Fix #347 - Suitecrm 8.4.0 validation on empty date fields

### LINKED ISSUE #347: Sutecrm 8.4.0 validation on empty date fields
#### Issue
When having multiple date fields in Account, we need some of them to stay empty. When saving i get “There are validation errors” message. Because of validation, we cannot save when editing the Account.

#### Expected Behavior
There should be no validation error message on empty date fields.

#### Actual Behavior
When saving empty date field i get “There are validation errors” message.

#### Possible Fix
Remove validation for empty date fields, when saving.

#### Steps to Reproduce
It was recognized by John as bug here:
https://community.suitecrm.com/t/sutecrm-8-4-empty-date-fields/90267/3

#### Context
This is a high priority bug for us.

#### Your Environment

* SuiteCRM Version used: 8.4.0
* Browser name and version Chrome 116.0.5845.179 (Uradna različica) (arm64), Safari, Firefox
* Environment name and version PHP 8.2. 
* Operating System and version Cpanel

### PR DESCRIPTION
**Pull request by TwizzX17**
I think my previous pull request got closed by an error. So here we go again.

On init of the date component, the field should default to null if empty. This is done by the condition checking function isVoid and isEmptyString. The last update to this file forgot to add an else to the next set value, that would override the previous setValue to null. This would result in an error triggered by the validation on save event. Because empty string is an invalid date. This fix will ensure the date is null or valid string date.

## Description

On init of the date component, the field should default to null if empty. This is done by the condition checking function isVoid and isEmptyString. The last update to this file forgot to add an else to the next set value, that would override the previous setValue to null. This would result in an error triggered by the validation on save event. Because empty string is an invalid date. This fix will ensure the date is null or valid string date.

## How To Test This

Add a date field to your form, this could be a custom field to Leads, Accounts, Contacts ...
If the date input field is empty on init and not filled out (not marked as required), the date field will be considered invalid by the validator.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by OliverJarvis97** [comment]
I am still getting validation errors upon testing this fix. To confirm, I cleared Symfony's cache and QR&R. Suite v8.4.0

**Comment by TwizzX17** [comment]
Hi @OliverJarvis97,
Are you sure it is the date component that is triggering the validation error? In Suitecrm v8.4.0, i cannot save forms with the standard email1 field, if it set to required. See my issue #352. if you remove the required checkmark, then it might work.

**Comment by OliverJarvis97** [comment]
Hi @TwizzX17 thanks for the reply,
It is not related to the other bug, as the email field isn't required on this module. The problem only exists when I try and save a record which has an empty date field - it returns a validation error. Inputting a date value allows me to save the record.

**Comment by jobrien2001** [comment]
I edited and did a quick repair.

I am still getting this:

image

**Comment by TwizzX17** [comment]
@jobrien2001 I am pretty sure you need to build the application from the command line. For development mode, you can run "npm run build-dev". @OliverJarvis97 did you build the application correctly?

**Comment by serhiisamko091184** [comment]
Hello @TwizzX17,

thanks for your contribution to SuiteCRM project!

Regards,
Serhii

**Review by clemente-raposo — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]

**Pull request merged**
