### PR TITLE
fix #305 - Fix issue with dropdowns not displaying correctly in listviews/dashlets

### LINKED ISSUE #305: MultiSelect/DropDown fields displayed with wrong values on paginated listviews in 8.3.0 and 8.3.1
#### Issue

When a MultiSelect field or DropDown is displayed in a paginated list, after the first page the values of the field are randomly mixed in different entries.

Note that the JSON of the GraphQL request always contains the values as expected. Please, find examples after the screenshots.

_(The following example is just an example, this also happens on relationship selection popup window and other places with list views... it seems to happen on any listview)_

**-> Example**

The contacts subpanel of a company with 12 contacts. Contacts have a custom MultiSelect filed called "Cargo" ("cargo_c") where possible values are the type of employee position (President/CEO/Manager/...).

First page of the contact list: all seems to be ok
image

Second page: showing wrong values.
image

Back to first page: now, first page also shows wrong values.
image

Back and forward, first page again: wrong values are shown in random positions.
image

GraphQL json always contains the expected values. Example of the last screenshot (relevant fragments):

```
{
    "data": {
        "getRecordList": {
            "id": "\/api\/record-list\/Contacts",
            "_id": "Contacts",
            "meta": {
                "offsets": {
                    "current": 0,
                    "next": 10,
                    "prev": -10,
                    "end": 10,
                    "total": 18,
                    "totalCounted": true
                },
                "ordering": {
                    "orderBy": "name",
                    "sortOrder": "ASC"
                }
            },
            "records": [
                {
                    "id": "a12a7810-3e83-3be6-cb37-64cb85342b41",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User A - manager",
[...]
                        "cargo_c": [
                            "Manager"
                        ],
[...]
                    },
[...]
                    }
                },
                {
                    "id": "81d8e73f-6e50-cc9e-38ca-64cb85d7c590",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User B - empty",
[...]
                        "cargo_c": [],
[...]
                    },
[...]
                },
                {
                    "id": "6f0c9735-ffa3-4862-60ce-64cb85f6c0c5",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User C - Director",
[...]
                        "cargo_c": [
                            "Director"
                        ],
[...]
                    },
[...]
                },
                {
                    "id": "c928c09a-43d9-5537-0cc8-64cb85be464a",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User D - empty",
[...]
                        "cargo_c": [],
[...]
                    },
[...]
                },
                {
                    "id": "8084b1c7-f427-82a3-d737-64cb854e5fc8",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User E - empty",
[...]
                        "cargo_c": [],
[...]
                    },
[...]
                },
                {
                    "id": "8f503e84-2e0b-69ad-49c9-64cb85a925da",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User F - empty",
[...]
                        "cargo_c": [],
[...]
                    },
[...]
                },
                {
                    "id": "83bc8d3b-4368-700a-c4cb-64cb85b498df",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User G - empty",
[...]
                        "cargo_c": [],
[...]
                    },
[...]
                },
                {
                    "id": "a8ede1d8-edae-0fe7-40e6-64cb85b2b2cf",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User H - empty",
[...]
                        "cargo_c": [],
[...]
                    },
[...]
                },
                {
                    "id": "e89af15a-4e43-3584-864c-64cb85634a40",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User I - empty",
[...]
                        "cargo_c": [],
[...]
                    },
[...]
                },
                {
                    "id": "3eb5b58d-87bf-4573-a568-64cb8649f577",
                    "module": "contacts",
                    "type": "Contact",
                    "attributes": {
[...]
                        "first_name": "User J - empty",
[...]
                        "cargo_c": [],
[...]
                    },
[...]
            ],
            "__typename": "RecordList"
        }
    }
}
```

#### Expected Behavior

The list view should show the MultiSelect/DropDown values selected on each item.

#### Actual Behavior

The list view randomly mixes the MultiSelect/DropDown values after page change.

#### Possible Fix

As GraphQL sends the values without error, this is probably a front-end JS bug.

#### Steps to Reproduce

1. (admin) Create a MultiSelect/DropDown field in contacts (for example)
2. (admin) Enable this MultiSelect/DropDown field in the company subpanel.
3. Find a company enough contacts to have pagination on the contact subpanel and edit one or more contacts from the first page to set a value in the MultiSelect/DropDown field.
4. Come back to the company and move forward/backward the pagination. The MultiSelect/DropDown fields will have wrong values.

#### Context

Easily find the CEO of a company by looking at the contacts subpanel.

Assign a relation to a contact/other.

We consider that this issue should be a high priority issue as it mixes data in the fronted in random order (not just "blank" fields). Also, it should be probably easy to fix as it seems to affect only to the front end (but I'm not sure about that).

#### Your Environment
* SuiteCRM Version used: 8.3.0/8.3.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 115.0.5790.110 / Mozilla Firefox 115.0.3 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04.6 LTS

### PR DESCRIPTION
**Pull request by JackBuchanan**
## Description
Fixes issue #305

Remove flag recycleRows to avoid cacheing of dropdown values on listviews and dashlets

## Motivation and Context
Remove flag recycleRows to avoid cacheing of dropdown values

## How To Test This
Add dropdown field to list view then Load More/Paigination to see more records
See that dropdowns display correctly

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by johnM2401 — APPROVED** [review]
LGTM, Checked both Dropdown and Multienum fields on both Listview & Subpanel views.

All Data seems to be accurate across pagination.

**Comment by bxpeter** [comment]
I can still reproduce this issue after applying the suggested PR.

Worth mentioning this applies to a custom field within the Project module.

**Comment by scicali** [comment]
> I can still reproduce this issue after applying the suggested PR.
> 
> Worth mentioning this applies to a custom field within the Project module.

Do you rebuild angular?

**Comment by bxpeter** [comment]
> > I can still reproduce this issue after applying the suggested PR.
> > Worth mentioning this applies to a custom field within the Project module.
> 
> Do you rebuild angular?

I didn't, but I have now. Works, thanks.

**Comment by bxpeter** [comment]
> > I can still reproduce this issue after applying the suggested PR.
> > Worth mentioning this applies to a custom field within the Project module.
> 
> Do you rebuild angular?

Changes are reverted after a studio change tho. Have to rebuild Angular again, only after adding an extra filter to the list view.
Is that expected behaviour?

**Comment by scicali** [comment]
> > > I can still reproduce this issue after applying the suggested PR.
> > > Worth mentioning this applies to a custom field within the Project module.
> > 
> > 
> > Do you rebuild angular?
> 
> Changes are reverted after a studio change tho. Have to rebuild Angular again, only after adding an extra filter to the list view. Is that expected behaviour?
No, you have to rebuild on angular changes only (like file in /core/app )

**Pull request merged**
