### PR TITLE
Fix #87 Fix language selection

### LINKED ISSUE #87: Language selection is not working on version 8.1
Language selection on login screen is not working, once you login it reverts to the default language.

#### Issue
When you install a new language pack (e.g. es_MX) so that the user may optionally switch languages on login, it doesn't work.

#### Expected Behavior
When a user gets to the login screen and selects a different language than the default language, and then logs in, the interface should reflect the language choice made by the user. 

#### Actual Behavior
When a user gets to the login screen, selects a different language, and logs in, the interface reverts to the default language

#### Steps to Reproduce
1. Install es_MX language pack
2. Logout
3. On the login screen, select Español as your language
4. Login with your credentials

#### Your Environment
* SuiteCRM Version used: 8.1
* PHP Version: 7.4.6
* Operating System and version: CentOS 8.3

### PR DESCRIPTION
**Pull request by clemente-raposo**
## Description

- Fix language selection
    - Was not being kept after login 
 - Fix  #87 
 
## Motivation and Context

 - Selected language not being kept after login. 
 - See  #87 
 
## How To Test This

- Login as administrator
- install a language pack
- logout and refresh
- The language selection dropdown should appear
- Select your newly installed language
- The ui should change to that new language
- Login
- The ui should still show the same language

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by johnM2401 — APPROVED** [review]
Looks good from a QA Perspective

Users can again install & use other languages

The last selected Langauge will be saved in cache for QOL

Looks good to go!

**Review by mattlorimer — CHANGES_REQUESTED** [review]
Legacy fixes to  

public/legacy/include/javascript/sugarwidgets/SugarYUIWidgets.js
public/legacy/jssource/src_files/include/javascript/sugarwidgets/SugarYUIWidgets.js
public/legacy/modules/Administration/templates/Languages.tpl
public/legacy/modules/Administration/views/view.languages.php

should be applied to legacy repo so they can be include in all releases

**Comment by clemente-raposo** [comment]
Hi @mattlorimer, thank you for the feedback.

I've created a MR on legacy with these changes:
- https://github.com/salesagility/SuiteCRM/pull/9584

I've also dropped the commit from this MR.

**Review by mattlorimer — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
Looks good to me

**Pull request merged**
