### PR TITLE
Fix #301 Contact not showing in Activities & history subpanel

### LINKED ISSUE #301: History and Activities subpanel not showing contacts
The contacts field is always empty for Calls Notes and Tasks even though a contact is related to them
#### Expected Behavior

The contacts field should not be empty in the activities and history subpanel

#### Actual Behavior
The contact field is empty for activities and history
The same issue on suite8demo as well

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 8.3.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 8.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu

Account:
image
Call:
image

### PR DESCRIPTION
**Pull request by lionfaris**
Change the rname in tasks, calls,  and Note to same as other Meetings

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hey @lionfaris,

thanks for your contribution! 

Regards,
Serhii

**Review by clemente-raposo — APPROVED** [review]

**Comment by clemente-raposo** [comment]
@johnM2401 when testing this it would be a good idea to see if there is any impacts on reports using calls, notes and tasks contacts

**Comment by johnM2401** [comment]
Hey folks!

So this appears to have resolved the issue on the Module->Activities and Module->History subpanels.

However, as @clemente-raposo suggested, I've had a look at Reports and it appears it may still be an issue here, but i'd like your guys' thoughts.

<br>

So, for example:

My Record "MTM Investment Bank F S B", has some of each Activity type, with a valid Contact showing:
image

However, on the Reports module, only the Tasks and Notes modules show their related Contact.
(I assume this is because they have a specific O2M Contact relate field, rather than grabbing an item from the Contacts subpanel as Activities&History now does)


So for example, this report:
image

Shows as so:
image


Whereas Tasks/Notes renders the contact correctly:
image
image

<br>

What are your thoughts, @clemente-raposo ?

Thanks!

**Comment by clemente-raposo** [comment]
Hi @johnM2401, as we spoke if it is behaving like before it should be ok. This fix should fix only on subpanels.

**Review by johnM2401 — APPROVED** [review]
Spoke w/ @clemente-raposo regarding this, LGTM!

**Pull request merged**
